[2024-11-18T06:47:56.631+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-11-18T06:47:55.465372+00:00 [queued]>
[2024-11-18T06:47:56.642+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-11-18T06:47:55.465372+00:00 [queued]>
[2024-11-18T06:47:56.642+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-18T06:47:56.654+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-11-18 06:47:55.465372+00:00
[2024-11-18T06:47:56.658+0000] {standard_task_runner.py:57} INFO - Started process 58 to run task
[2024-11-18T06:47:56.661+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-11-18T06:47:55.465372+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpzp2ff0k9']
[2024-11-18T06:47:56.665+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask reddit_extraction
[2024-11-18T06:47:56.783+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-11-18T06:47:55.465372+00:00 [running]> on host 9f42dd3b4e06
[2024-11-18T06:47:56.877+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bao Nguyen' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T06:47:55.465372+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T06:47:55.465372+00:00'
[2024-11-18T06:47:56.879+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: reddit_pipeline() missing 1 required positional argument: 'sil_name'
[2024-11-18T06:47:56.890+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, execution_date=20241118T064755, start_date=20241118T064756, end_date=20241118T064756
[2024-11-18T06:47:56.904+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task reddit_extraction (reddit_pipeline() missing 1 required positional argument: 'sil_name'; 58)
[2024-11-18T06:47:56.931+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-18T06:47:56.953+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
