[2024-11-18T06:49:10.249+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-11-18T06:49:08.969007+00:00 [queued]>
[2024-11-18T06:49:10.260+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-11-18T06:49:08.969007+00:00 [queued]>
[2024-11-18T06:49:10.261+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-18T06:49:10.274+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-11-18 06:49:08.969007+00:00
[2024-11-18T06:49:10.278+0000] {standard_task_runner.py:57} INFO - Started process 63 to run task
[2024-11-18T06:49:10.282+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-11-18T06:49:08.969007+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpxcg971x1']
[2024-11-18T06:49:10.283+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask reddit_extraction
[2024-11-18T06:49:10.336+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-11-18T06:49:08.969007+00:00 [running]> on host 9f42dd3b4e06
[2024-11-18T06:49:10.408+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bao Nguyen' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T06:49:08.969007+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T06:49:08.969007+00:00'
[2024-11-18T06:49:10.409+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: reddit_pipeline() missing 1 required positional argument: 'sil_name'
[2024-11-18T06:49:10.416+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, execution_date=20241118T064908, start_date=20241118T064910, end_date=20241118T064910
[2024-11-18T06:49:10.425+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task reddit_extraction (reddit_pipeline() missing 1 required positional argument: 'sil_name'; 63)
[2024-11-18T06:49:10.465+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-18T06:49:10.484+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
